[tool.poetry]
name = "wonda"
version = "0.5.7"
description = "Asynchronous feature-rich Telegram bot framework for building great bots"
authors = []
license = "MIT"
readme = "README.md"
homepage = "https://github.com/wondergram-org/wonda/"

[tool.poetry.dependencies]
python = "^3.8"
certifi = "^2022.6.15"
choicelib = "^0.1.5"
aiohttp = "^3.8.1"
pydantic = "^1.10.4"
typing-extensions = "^4.3.0"
envparse = "^0.2.0"
uvloop = {version = "^0.16.0", optional = true}
watchfiles = {version = "^0.16.0", optional = true}
orjson = {version = "^3.8.5", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.6.0"

[tool.poetry.extras]
auto-reload = ["watchfiles"]
power-ups = ["orjson", "uvloop"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
